#!/usr/bin/expect

set timeout 10 


# Get.exp IPaddress userID userPasswd 

spawn /usr/bin/ssh [lindex $argv 1]@[lindex $argv 0]
sleep 3
#expect "Username:"
#send "[lindex $argv 1]\r"
expect "word:"
send "[lindex $argv 2]\r"
expect ">"
send "vlan port [lindex $argv 3] 802.1x disable\r"
expect ">"
send "vlan [lindex $argv 4] port default [lindex $argv 3]\r"
expect ">"
send "write memory \r"
expect ">"
send "copy working certified \r"
expect ">"
send "exit\r"
expect ":"
