#!/usr/bin/expect

set timeout 10 


# Get.exp IPaddress userID userPasswd 

spawn /usr/bin/ssh [lindex $argv 1]@[lindex $argv 0]
#expect "Username:"
#send "[lindex $argv 1]\r"
expect "word:"
send "[lindex $argv 2]\r"
expect "#"
send "service status all\r"
expect "#"
send "network nslookup google.com \r"
expect "#"
send "network ping 10.225.66.12 \r"
expect "#"
send "show sysinfo \r"
expect "#"

send "exit\r"
