#!/usr/bin/expect

set timeout 10 


# Get.exp IPaddress userID userPasswd 

spawn /usr/bin/ssh [lindex $argv 1]@[lindex $argv 0]
sleep 2
#expect "Username:"
#send "[lindex $argv 1] \r"
#expect "word:"
expect "word:"
send "[lindex $argv 2]\r"
expect ">"
send "en\r"
expect "word:"
send "[lindex $argv 3]\r"
expect "#"
send "terminal leng 0\r"
expect "#"
send "show int status\r"
expect "#"
send "terminal leng 30\r"
expect "#"
send "exit\r"
#expect ">"
#send "exit\r"
