#!/usr/bin/expect

set timeout 10 


# Get.exp IPaddress userID userPasswd enablePasswd

spawn /usr/bin/ssh [lindex $argv 1]@[lindex $argv 0]
sleep 30

#expect "Username:"
#send "[lindex $argv 1]\r"
expect "word"
send "[lindex $argv 2]\r"
expect ">"
send "en\r"
expect "word"
send "[lindex $argv 3]\r"
expect "#"
send "terminal length 0\r"
expect "#"
send "show run\r"
expect "#"
send "terminal length 50\r"
expect "#"
#send "show tech\r"
#expect "#"

send "exit\r"
